ALTER TABLE home_stats    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE home_stats    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE home_features ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE home_features ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE home_roadmap  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE home_roadmap  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;